name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u BrentSchoeters --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/brentschoeters/skills2-2:${GITHUB_SHA} .

      - name: Push image
        run: docker push ghcr.io/brentschoeters/skills2-2:${GITHUB_SHA}
